version: "3.6"

services:
    reverse-proxy:
        image: traefik
        ports:
            - "80:80"
            - "8080:8080"
        networks:
            - ${NETWORK_NAME:-demo}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./.docker/traefik.yml:/etc/traefik/traefik.yml

    db:
        image: mysql:8
        networks:
            - ${NETWORK_NAME:-demo}
        command:
          [
              "--character-set-server=utf8mb4",
              "--collation-server=utf8mb4_unicode_ci",
              "--default-authentication-plugin=mysql_native_password",
              "--default_password_lifetime=0"
          ]

        volumes:
            - ./.docker/mysql:/var/lib/mysql
        ports:
            - ${DB_PORT:-3306}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-demo}
            MYSQL_USER: ${MYSQL_USER:-demo}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-demo}

    php-fpm:
        environment:
            XDEBUG_ENABLED: ${XDEBUG_ENABLED:-0}
        build:
            context: ./.docker/php-fpm
        networks:
            - ${NETWORK_NAME:-demo}
        volumes:
            - .:/var/www/app:cached
        links:
            - db:mysql.docker

    nginx:
        build:
            context: ./.docker/nginx
        networks:
            - ${NETWORK_NAME:-demo}
        links:
            - php-fpm:php-fpm.local
        labels:
            traefik.http.routers.nginx.rule: "Host(`demo.docker.localhost`)"

    mailDev:
        image: djfarrelly/maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        networks:
            - ${NETWORK_NAME:-demo}
        ports:
            - "81:80"
        labels:
            traefik.http.routers.mailDev.rule: "Host(`mail.demo.docker.localhost`)"

networks:
    demo:
        name: ${NETWORK_NAME:-demo}
        external: true
