name: Main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  APP_ENV: test
  XDEBUG_ENABLED: 1
  DOCKER_COMPOSER_USER: root

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Init
        env:
          GITLAB_LOGIN: ${{ secrets.GITLAB_LOGIN }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        run: make init-docker

      - name: Install
        run: make up install

      - name: Wait mysql
        run: docker-compose exec -T db timeout 15 sh -c "while ! mysqladmin ping; do sleep 1 && echo -n .; done;"

      - name: Quality
        run: make lint phpmd

      - name: Test
        run: make fixtures-reset test

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: .build/clover.xml

      - name: Clean
        run: make down
