name: Main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  APP_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Init
        env:
          GITLAB_LOGIN: ${{ secrets.GITLAB_LOGIN }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        run: make init

      - name: Install
        run: make up

      - name: Lint
        run: make lint
